### ISSUE TITLE
Remove overlapping of rugae/shapes of different classes

### ISSUE THREAD

**Issue by joaoherrera** [laradru/ai-palatal-rugoscopy#31]
There's an NMS (Non-Maximum Suppression) algorithm being applied intra-class so we don't end up with shapes overlapping. 

However, we are still seeing overlapping rugae/shapes of different classes.

We need to apply an inter-class NMS algorithm.

**Comment by brunodrugowick** [comment]
João is doing his own RANMS (Really Agnostic NMS).
