### ISSUE TITLE
Remove tiny shapes that are certainly not a rugae

### ISSUE THREAD

**Issue by brunodrugowick** [laradru/ai-palatal-rugoscopy#34]
We need to make sure that we consider the relative size of the shape/rugae, but this definition can be empirical.

**Comment by brunodrugowick** [comment]
@joaoherrera , what did we discuss about this on our last meeting? Can we recordo it here?

I remember we said something about what needs to be externalized as a configuration, at least.

**Comment by brunodrugowick** [comment]
This is an histogram of the area of all annotations from the "manual" dataset:

![Histogram of Area](https://docs.google.com/spreadsheets/d/e/2PACX-1vRDg_PbrxJEUtZjVbXWCQImrsk-51TW-4BFCC4WFLKKcjr0pZBfw0wg7rykwxVf_J2P1e96C_i6oVkP/pubchart?oid=1537154084&format=image)

Smallest annotation area (absolute) is 148.

**Comment by brunodrugowick** [comment]
Histogram of the relative percentage of the annotation in its image:

![Histogram percent](https://docs.google.com/spreadsheets/d/e/2PACX-1vRDg_PbrxJEUtZjVbXWCQImrsk-51TW-4BFCC4WFLKKcjr0pZBfw0wg7rykwxVf_J2P1e96C_i6oVkP/pubchart?oid=1542276600&format=image)

**Comment by brunodrugowick** [comment]
Smallest annotation info:
Area: 148.00
Image area: 12192768.00
Relative percentage: 0.00121383429915175958
Image ID: 687

Biggest annotation info:
Area: 357134.00
Image area: 12192768.00
Relative percentage: 2.92906417968421939335
Image ID: 44

**Comment by joaoherrera** [comment]
> [@joaoherrera](https://github.com/joaoherrera) , what did we discuss about this on our last meeting? Can we recordo it here?
> 
> I remember we said something about what needs to be externalized as a configuration, at least.

The main idea is to use a parameter to compare how big the annotations are. In that case, we discussed about the value 1024, which is used to normalize the input image size. A threshold will be necessary to accept/reject the annotation.

**Comment by joaoherrera** [comment]
Sorry for the late reply. I didn't receive any notification about these questions.
