### ISSUE TITLE
Join patches into a single image

### ISSUE THREAD

**Issue by joaoherrera** [laradru/ai-palatal-rugoscopy#9]
Given a set of patches as binary masks, join them into a single image. Example:

Input:
- List of image patches (`List[np.ndarray]`)
- List of patch names (`List[str]`). Each patch name will follow the pattern: `imagename_x_y.jpg`, where x and y are the top-left coordinate in the original image.

![Image](https://github.com/laradru/ai-palatal-rugoscopy/assets/26142253/c1ef5f3a-4ddd-4e3e-84fd-b4593a2d860a)

Output:
- A single mask (`np.ndarray`).

<div align="center">
<img src=https://github.com/laradru/ai-palatal-rugoscopy/assets/26142253/91c21c9f-4f29-4da8-9277-2524e296d8a7>
</div>

**Comment by brunodrugowick** [comment]
Is the algorithm supposed to merge the patches and sum the binary values (assuming 0 and 1 for black and white respectively) when they match the same x and y values of the image?

@joaoherrera
